name: Trigger UCB

on:
  push:
    tags:
    - '*build*'
    
  workflow_dispatch:
    
jobs:
  sendtounity:


#  if: contains(github.event.head_commit.message, '[test]')
    runs-on: ubuntu-latest
    env: 
      MYCOMMIT: ${{ github.event.head.sha || github.sha }}      
    
    steps:
      - name: test message
        run: echo "TESTING {\"commit\":\"$MYCOMMIT\"}"
      - name: tell unity to pull
        run: |
          curl -X POST \
            -d '{"clean":true,"delay":30}' \
            -H "Content-Type: application/json" \
            -H "Authorization: Basic ${{ secrets.API_KEY }}" \
            "https://build-api.cloud.unity3d.com/api/v1/orgs/${{ vars.ORG_ID }}/projects/${{ vars.PROJ_ID }}/buildtargets/${{ vars.BUILD_ID }}/builds"
